name: MBStockAppBuildAndTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run tests on iPhone 15 Simulator with iOS 17.6
    - name: Run Tests on iPhone 15 Simulator (iOS 17.6)
      run: |
        xcodebuild test \
          -scheme 'Requestify' \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.6'
