name: MBStockAppBuildAndTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    # Run tests on iPhone 15 Simulator with iOS 16.0
    - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
      run: |
        xcodebuild test \
          -scheme 'Requestify' \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
